job:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DATA_MANAGEMENT_URL: https://pip-data-management.staging.platform.hmcts.net
    TRIGGER_TYPE: CLEAR_AUDIT_TABLE
